//dummy flight search results
export const flightResults = [
    {
        id: 1,
        airline: 'Emirates',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/d/d0/Emirates_logo.svg',
        flightNumber: 'EK-585',
        fromCode: 'DAC',
        fromCity: 'Dhaka',
        toCode: 'JFK',
        toCity: 'New York',
        departureTime: '10:00 AM',
        arrivalTime: '04:00 PM',
        duration: '20h 30m',
        price: 1250,
        stops: 1,
        stopInfo: 'Via Dubai (DXB) • 2h 15m Layover',
        legs: [
            { from: 'DAC', to: 'DXB', duration: '5h 30m', airline: 'Emirates' },
            { from: 'DXB', to: 'JFK', duration: '14h 00m', airline: 'Emirates' },
        ],
    },
    {
        id: 2,
        airline: 'Qatar Airways',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/c/c2/Qatar_Airways_Logo.png', // Use valid URL
        flightNumber: 'QR-640',
        fromCode: 'DAC',
        fromCity: 'Dhaka',
        toCode: 'JFK',
        toCity: 'New York',
        departureTime: '08:00 PM',
        arrivalTime: '02:00 PM', // Next day
        duration: '22h 00m',
        price: 1180,
        stops: 1,
        stopInfo: 'Via Doha (DOH) • 3h 00m Layover',
        legs: [
            { from: 'DAC', to: 'DOH', duration: '6h 00m', airline: 'Qatar Airways' },
            { from: 'DOH', to: 'JFK', duration: '13h 00m', airline: 'Qatar Airways' },
        ],
    },
    {
        id: 3,
        airline: 'Biman Bangladesh',
        logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e7/Biman_Bangladesh_Airlines_logo.svg/1200px-Biman_Bangladesh_Airlines_logo.svg.png',
        flightNumber: 'BG-301',
        fromCode: 'DAC',
        fromCity: 'Dhaka',
        toCode: 'LHR',
        toCity: 'London',
        departureTime: '11:30 AM',
        arrivalTime: '05:00 PM',
        duration: '11h 30m',
        price: 950,
        stops: 0, // Direct Flight
        stopInfo: 'Non-stop',
        legs: [],
    },
    {
        id: 4,
        airline: 'Turkish Airlines',
        logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Turkish_Airlines_logo_2019_compact.svg/2560px-Turkish_Airlines_logo_2019_compact.svg.png',
        flightNumber: 'TK-713',
        fromCode: 'DAC',
        fromCity: 'Dhaka',
        toCode: 'YYZ',
        toCity: 'Toronto',
        departureTime: '06:00 AM',
        arrivalTime: '09:00 PM',
        duration: '26h 15m',
        price: 1450,
        stops: 2,
        stopInfo: '2 Stops (IST, LHR)',
        legs: [
            { from: 'DAC', to: 'IST', duration: '9h 00m', airline: 'Turkish' },
            { from: 'IST', to: 'LHR', duration: '4h 00m', airline: 'Turkish' },
            { from: 'LHR', to: 'YYZ', duration: '8h 00m', airline: 'Air Canada' },
        ],
    },
];


// Popular airport suggestions for flight search
export const airportSuggestions = Object.freeze([
    // --- Bangladesh (Domestic & Intl) ---
    { code: 'DAC', city: 'Dhaka', name: 'Hazrat Shahjalal Intl Airport', country: 'Bangladesh' },
    { code: 'CGP', city: 'Chittagong', name: 'Shah Amanat Intl Airport', country: 'Bangladesh' },
    { code: 'CXB', city: "Cox's Bazar", name: "Cox's Bazar Airport", country: 'Bangladesh' },
    { code: 'ZYL', city: 'Sylhet', name: 'Osmani Intl Airport', country: 'Bangladesh' },
    { code: 'JSR', city: 'Jashore', name: 'Jashore Airport', country: 'Bangladesh' },
    { code: 'RJH', city: 'Rajshahi', name: 'Shah Makhdum Airport', country: 'Bangladesh' },
    { code: 'SPD', city: 'Saidpur', name: 'Saidpur Airport', country: 'Bangladesh' },
    { code: 'BZL', city: 'Barishal', name: 'Barishal Airport', country: 'Bangladesh' },

    // --- Middle East (Popular for BD Travelers) ---
    { code: 'JED', city: 'Jeddah', name: 'King Abdulaziz Intl Airport', country: 'Saudi Arabia' },
    {
        code: 'MED',
        city: 'Madinah',
        name: 'Prince Mohammad Bin Abdulaziz',
        country: 'Saudi Arabia',
    },
    { code: 'RUH', city: 'Riyadh', name: 'King Khalid Intl Airport', country: 'Saudi Arabia' },
    { code: 'DMM', city: 'Dammam', name: 'King Fahd Intl Airport', country: 'Saudi Arabia' },
    { code: 'DXB', city: 'Dubai', name: 'Dubai Intl Airport', country: 'UAE' },
    { code: 'AUH', city: 'Abu Dhabi', name: 'Zayed Intl Airport', country: 'UAE' },
    { code: 'SHJ', city: 'Sharjah', name: 'Sharjah Intl Airport', country: 'UAE' },
    { code: 'DOH', city: 'Doha', name: 'Hamad Intl Airport', country: 'Qatar' },
    { code: 'MCT', city: 'Muscat', name: 'Muscat Intl Airport', country: 'Oman' },
    { code: 'KWI', city: 'Kuwait City', name: 'Kuwait Intl Airport', country: 'Kuwait' },
    { code: 'BAH', city: 'Manama', name: 'Bahrain Intl Airport', country: 'Bahrain' },
    { code: 'IST', city: 'Istanbul', name: 'Istanbul Airport', country: 'Turkey' },
    { code: 'SAW', city: 'Istanbul', name: 'Sabiha Gokcen Intl Airport', country: 'Turkey' },
    { code: 'AMM', city: 'Amman', name: 'Queen Alia Intl Airport', country: 'Jordan' },
    { code: 'BEY', city: 'Beirut', name: 'Rafic Hariri Intl Airport', country: 'Lebanon' },
    { code: 'BGW', city: 'Baghdad', name: 'Baghdad Intl Airport', country: 'Iraq' },
    { code: 'THR', city: 'Tehran', name: 'Mehrabad Intl Airport', country: 'Iran' },
    { code: 'IKA', city: 'Tehran', name: 'Imam Khomeini Intl Airport', country: 'Iran' },

    // --- India & South Asia ---
    { code: 'CCU', city: 'Kolkata', name: 'Netaji Subhash Chandra Bose Intl', country: 'India' },
    { code: 'DEL', city: 'New Delhi', name: 'Indira Gandhi Intl Airport', country: 'India' },
    { code: 'BOM', city: 'Mumbai', name: 'Chhatrapati Shivaji Maharaj Intl', country: 'India' },
    { code: 'MAA', city: 'Chennai', name: 'Chennai Intl Airport', country: 'India' },
    { code: 'BLR', city: 'Bangalore', name: 'Kempegowda Intl Airport', country: 'India' },
    { code: 'HYD', city: 'Hyderabad', name: 'Rajiv Gandhi Intl Airport', country: 'India' },
    { code: 'KTM', city: 'Kathmandu', name: 'Tribhuvan Intl Airport', country: 'Nepal' },
    { code: 'CMB', city: 'Colombo', name: 'Bandaranaike Intl Airport', country: 'Sri Lanka' },
    { code: 'MLE', city: 'Male', name: 'Velana Intl Airport', country: 'Maldives' },
    { code: 'KHI', city: 'Karachi', name: 'Jinnah Intl Airport', country: 'Pakistan' },
    { code: 'LHE', city: 'Lahore', name: 'Allama Iqbal Intl Airport', country: 'Pakistan' },
    { code: 'ISB', city: 'Islamabad', name: 'Islamabad Intl Airport', country: 'Pakistan' },
    { code: 'PBH', city: 'Paro', name: 'Paro Airport', country: 'Bhutan' },

    // --- Southeast Asia ---
    { code: 'BKK', city: 'Bangkok', name: 'Suvarnabhumi Airport', country: 'Thailand' },
    { code: 'DMK', city: 'Bangkok', name: 'Don Mueang Intl Airport', country: 'Thailand' },
    { code: 'HKT', city: 'Phuket', name: 'Phuket Intl Airport', country: 'Thailand' },
    { code: 'SIN', city: 'Singapore', name: 'Changi Airport', country: 'Singapore' },
    { code: 'KUL', city: 'Kuala Lumpur', name: 'Kuala Lumpur Intl Airport', country: 'Malaysia' },
    { code: 'LGK', city: 'Langkawi', name: 'Langkawi Intl Airport', country: 'Malaysia' },
    { code: 'CGK', city: 'Jakarta', name: 'Soekarno-Hatta Intl Airport', country: 'Indonesia' },
    { code: 'DPS', city: 'Bali', name: 'Ngurah Rai Intl Airport', country: 'Indonesia' },
    { code: 'MNL', city: 'Manila', name: 'Ninoy Aquino Intl Airport', country: 'Philippines' },
    {
        code: 'SGN',
        city: 'Ho Chi Minh City',
        name: 'Tan Son Nhat Intl Airport',
        country: 'Vietnam',
    },
    { code: 'HAN', city: 'Hanoi', name: 'Noi Bai Intl Airport', country: 'Vietnam' },

    // --- East Asia ---
    { code: 'PEK', city: 'Beijing', name: 'Beijing Capital Intl Airport', country: 'China' },
    { code: 'PVG', city: 'Shanghai', name: 'Pudong Intl Airport', country: 'China' },
    { code: 'CAN', city: 'Guangzhou', name: 'Baiyun Intl Airport', country: 'China' },
    { code: 'HKG', city: 'Hong Kong', name: 'Hong Kong Intl Airport', country: 'Hong Kong' },
    { code: 'HND', city: 'Tokyo', name: 'Haneda Airport', country: 'Japan' },
    { code: 'NRT', city: 'Tokyo', name: 'Narita Intl Airport', country: 'Japan' },
    { code: 'KIX', city: 'Osaka', name: 'Kansai Intl Airport', country: 'Japan' },
    { code: 'ICN', city: 'Seoul', name: 'Incheon Intl Airport', country: 'South Korea' },
    { code: 'TPE', city: 'Taipei', name: 'Taoyuan Intl Airport', country: 'Taiwan' },

    // --- Europe (Major Hubs) ---
    { code: 'LHR', city: 'London', name: 'Heathrow Airport', country: 'UK' },
    { code: 'LGW', city: 'London', name: 'Gatwick Airport', country: 'UK' },
    { code: 'MAN', city: 'Manchester', name: 'Manchester Airport', country: 'UK' },
    { code: 'CDG', city: 'Paris', name: 'Charles de Gaulle Airport', country: 'France' },
    { code: 'ORY', city: 'Paris', name: 'Orly Airport', country: 'France' },
    { code: 'FRA', city: 'Frankfurt', name: 'Frankfurt Airport', country: 'Germany' },
    { code: 'MUC', city: 'Munich', name: 'Munich Airport', country: 'Germany' },
    { code: 'BER', city: 'Berlin', name: 'Berlin Brandenburg Airport', country: 'Germany' },
    { code: 'AMS', city: 'Amsterdam', name: 'Schiphol Airport', country: 'Netherlands' },
    { code: 'FCO', city: 'Rome', name: 'Leonardo da Vinci-Fiumicino', country: 'Italy' },
    { code: 'MXP', city: 'Milan', name: 'Malpensa Airport', country: 'Italy' },
    { code: 'MAD', city: 'Madrid', name: 'Adolfo Suárez Madrid-Barajas', country: 'Spain' },
    {
        code: 'BCN',
        city: 'Barcelona',
        name: 'Josep Tarradellas Barcelona-El Prat',
        country: 'Spain',
    },
    { code: 'ZRH', city: 'Zurich', name: 'Zurich Airport', country: 'Switzerland' },
    { code: 'GVA', city: 'Geneva', name: 'Geneva Airport', country: 'Switzerland' },
    { code: 'VIE', city: 'Vienna', name: 'Vienna Intl Airport', country: 'Austria' },
    { code: 'BRU', city: 'Brussels', name: 'Brussels Airport', country: 'Belgium' },
    { code: 'CPH', city: 'Copenhagen', name: 'Copenhagen Airport', country: 'Denmark' },
    { code: 'OSL', city: 'Oslo', name: 'Oslo Airport', country: 'Norway' },
    { code: 'ARN', city: 'Stockholm', name: 'Arlanda Airport', country: 'Sweden' },
    { code: 'HEL', city: 'Helsinki', name: 'Helsinki-Vantaa Airport', country: 'Finland' },
    { code: 'ATH', city: 'Athens', name: 'Athens Intl Airport', country: 'Greece' },
    { code: 'LIS', city: 'Lisbon', name: 'Humberto Delgado Airport', country: 'Portugal' },
    { code: 'DUB', city: 'Dublin', name: 'Dublin Airport', country: 'Ireland' },
    { code: 'SVO', city: 'Moscow', name: 'Sheremetyevo Intl Airport', country: 'Russia' },
    { code: 'WAW', city: 'Warsaw', name: 'Chopin Airport', country: 'Poland' },

    // --- North America (USA & Canada) ---
    { code: 'JFK', city: 'New York', name: 'John F. Kennedy Intl Airport', country: 'USA' },
    { code: 'EWR', city: 'Newark', name: 'Newark Liberty Intl Airport', country: 'USA' },
    { code: 'LGA', city: 'New York', name: 'LaGuardia Airport', country: 'USA' },
    { code: 'LAX', city: 'Los Angeles', name: 'Los Angeles Intl Airport', country: 'USA' },
    { code: 'SFO', city: 'San Francisco', name: 'San Francisco Intl Airport', country: 'USA' },
    { code: 'ORD', city: 'Chicago', name: "O'Hare Intl Airport", country: 'USA' },
    { code: 'MIA', city: 'Miami', name: 'Miami Intl Airport', country: 'USA' },
    { code: 'MCO', city: 'Orlando', name: 'Orlando Intl Airport', country: 'USA' },
    { code: 'LAS', city: 'Las Vegas', name: 'Harry Reid Intl Airport', country: 'USA' },
    { code: 'ATL', city: 'Atlanta', name: 'Hartsfield-Jackson Intl', country: 'USA' },
    { code: 'DFW', city: 'Dallas', name: 'Dallas/Fort Worth Intl', country: 'USA' },
    { code: 'IAH', city: 'Houston', name: 'George Bush Intercontinental', country: 'USA' },
    { code: 'IAD', city: 'Washington', name: 'Dulles Intl Airport', country: 'USA' },
    { code: 'BOS', city: 'Boston', name: 'Logan Intl Airport', country: 'USA' },
    { code: 'SEA', city: 'Seattle', name: 'Seattle-Tacoma Intl', country: 'USA' },
    { code: 'YYZ', city: 'Toronto', name: 'Pearson Intl Airport', country: 'Canada' },
    { code: 'YVR', city: 'Vancouver', name: 'Vancouver Intl Airport', country: 'Canada' },
    { code: 'YUL', city: 'Montreal', name: 'Pierre Elliott Trudeau Intl', country: 'Canada' },

    // --- Oceania ---
    { code: 'SYD', city: 'Sydney', name: 'Kingsford Smith Airport', country: 'Australia' },
    { code: 'MEL', city: 'Melbourne', name: 'Melbourne Airport', country: 'Australia' },
    { code: 'BNE', city: 'Brisbane', name: 'Brisbane Airport', country: 'Australia' },
    { code: 'PER', city: 'Perth', name: 'Perth Airport', country: 'Australia' },
    { code: 'AKL', city: 'Auckland', name: 'Auckland Airport', country: 'New Zealand' },

    // --- Africa ---
    { code: 'CAI', city: 'Cairo', name: 'Cairo Intl Airport', country: 'Egypt' },
    { code: 'JNB', city: 'Johannesburg', name: 'O.R. Tambo Intl Airport', country: 'South Africa' },
    { code: 'CPT', city: 'Cape Town', name: 'Cape Town Intl Airport', country: 'South Africa' },
    { code: 'CMN', city: 'Casablanca', name: 'Mohammed V Intl Airport', country: 'Morocco' },
    { code: 'LOS', city: 'Lagos', name: 'Murtala Muhammed Intl Airport', country: 'Nigeria' },
    { code: 'NBO', city: 'Nairobi', name: 'Jomo Kenyatta Intl Airport', country: 'Kenya' },
    { code: 'ADD', city: 'Addis Ababa', name: 'Bole Intl Airport', country: 'Ethiopia' },

    // --- South America ---
    { code: 'GRU', city: 'São Paulo', name: 'Guarulhos Intl Airport', country: 'Brazil' },
    { code: 'GIG', city: 'Rio de Janeiro', name: 'Galeão Intl Airport', country: 'Brazil' },
    { code: 'EZE', city: 'Buenos Aires', name: 'Ezeiza Intl Airport', country: 'Argentina' },
    { code: 'BOG', city: 'Bogotá', name: 'El Dorado Intl Airport', country: 'Colombia' },
    { code: 'LIM', city: 'Lima', name: 'Jorge Chávez Intl Airport', country: 'Peru' },
    { code: 'SCL', city: 'Santiago', name: 'Arturo Merino Benítez Intl', country: 'Chile' },

    // --- More USA/Europe/Asia filler for Volume ---
    { code: 'DEN', city: 'Denver', name: 'Denver Intl Airport', country: 'USA' },
    { code: 'PHX', city: 'Phoenix', name: 'Sky Harbor Intl Airport', country: 'USA' },
    { code: 'CLT', city: 'Charlotte', name: 'Douglas Intl Airport', country: 'USA' },
    { code: 'DTW', city: 'Detroit', name: 'Metropolitan Wayne County', country: 'USA' },
    { code: 'MSP', city: 'Minneapolis', name: 'Saint Paul Intl Airport', country: 'USA' },
    { code: 'PHL', city: 'Philadelphia', name: 'Philadelphia Intl Airport', country: 'USA' },
    { code: 'SAN', city: 'San Diego', name: 'San Diego Intl Airport', country: 'USA' },
    { code: 'TPA', city: 'Tampa', name: 'Tampa Intl Airport', country: 'USA' },
    { code: 'HNL', city: 'Honolulu', name: 'Daniel K. Inouye Intl', country: 'USA' },
    { code: 'DUS', city: 'Düsseldorf', name: 'Düsseldorf Airport', country: 'Germany' },
    { code: 'HAM', city: 'Hamburg', name: 'Hamburg Airport', country: 'Germany' },
    { code: 'STR', city: 'Stuttgart', name: 'Stuttgart Airport', country: 'Germany' },
    { code: 'LYS', city: 'Lyon', name: 'Saint-Exupéry Airport', country: 'France' },
    { code: 'NCE', city: 'Nice', name: "Côte d'Azur Airport", country: 'France' },
    { code: 'MRS', city: 'Marseille', name: 'Provence Airport', country: 'France' },
    { code: 'VCE', city: 'Venice', name: 'Marco Polo Airport', country: 'Italy' },
    { code: 'NAP', city: 'Naples', name: 'Naples Intl Airport', country: 'Italy' },
    { code: 'PMO', city: 'Palermo', name: 'Falcone Borsellino Airport', country: 'Italy' },
    { code: 'AGP', city: 'Málaga', name: 'Málaga-Costa del Sol Airport', country: 'Spain' },
    { code: 'VLC', city: 'Valencia', name: 'Valencia Airport', country: 'Spain' },
    { code: 'SVQ', city: 'Seville', name: 'Seville Airport', country: 'Spain' },
    { code: 'GKA', city: 'Goroka', name: 'Goroka Airport', country: 'Papua New Guinea' },
    { code: 'MAG', city: 'Madang', name: 'Madang Airport', country: 'Papua New Guinea' },
    { code: 'HGU', city: 'Mount Hagen', name: 'Mount Hagen Airport', country: 'Papua New Guinea' },
    { code: 'LAE', city: 'Nadzab', name: 'Nadzab Airport', country: 'Papua New Guinea' },
    {
        code: 'POM',
        city: 'Port Moresby',
        name: 'Jacksons Intl Airport',
        country: 'Papua New Guinea',
    },
    { code: 'WWK', city: 'Wewak', name: 'Wewak Airport', country: 'Papua New Guinea' },
    { code: 'UAK', city: 'Narsarsuaq', name: 'Narsarsuaq Airport', country: 'Greenland' },
    { code: 'GOH', city: 'Nuuk', name: 'Nuuk Airport', country: 'Greenland' },
    { code: 'SFJ', city: 'Kangerlussuaq', name: 'Kangerlussuaq Airport', country: 'Greenland' },
    { code: 'THU', city: 'Thule', name: 'Thule Air Base', country: 'Greenland' },
    { code: 'AEY', city: 'Akureyri', name: 'Akureyri Airport', country: 'Iceland' },
    { code: 'EGS', city: 'Egilsstaðir', name: 'Egilsstaðir Airport', country: 'Iceland' },
    { code: 'HFN', city: 'Höfn', name: 'Hornafjörður Airport', country: 'Iceland' },
    { code: 'KEF', city: 'Reykjavik', name: 'Keflavík Intl Airport', country: 'Iceland' },
    { code: 'RKV', city: 'Reykjavik', name: 'Reykjavík Airport', country: 'Iceland' },
    { code: 'YEG', city: 'Edmonton', name: 'Edmonton Intl Airport', country: 'Canada' },
    { code: 'YHZ', city: 'Halifax', name: 'Stanfield Intl Airport', country: 'Canada' },
    { code: 'YOW', city: 'Ottawa', name: 'Macdonald-Cartier Intl', country: 'Canada' },
    { code: 'YYC', city: 'Calgary', name: 'Calgary Intl Airport', country: 'Canada' },
    { code: 'YWG', city: 'Winnipeg', name: 'James Armstrong Richardson', country: 'Canada' },
    { code: 'MEX', city: 'Mexico City', name: 'Benito Juárez Intl', country: 'Mexico' },
    { code: 'CUN', city: 'Cancún', name: 'Cancún Intl Airport', country: 'Mexico' },
    { code: 'GDL', city: 'Guadalajara', name: 'Miguel Hidalgo y Costilla', country: 'Mexico' },
    { code: 'PTY', city: 'Panama City', name: 'Tocumen Intl Airport', country: 'Panama' },
    { code: 'SJO', city: 'San José', name: 'Juan Santamaría Intl', country: 'Costa Rica' },
    { code: 'HAV', city: 'Havana', name: 'José Martí Intl Airport', country: 'Cuba' },
    {
        code: 'PUJ',
        city: 'Punta Cana',
        name: 'Punta Cana Intl Airport',
        country: 'Dominican Republic',
    },
    {
        code: 'SDQ',
        city: 'Santo Domingo',
        name: 'Las Américas Intl',
        country: 'Dominican Republic',
    },
    { code: 'SJU', city: 'San Juan', name: 'Luis Muñoz Marín Intl', country: 'Puerto Rico' },
    { code: 'KINGS', city: 'Kingston', name: 'Norman Manley Intl', country: 'Jamaica' },
    { code: 'MBJ', city: 'Montego Bay', name: 'Sangster Intl Airport', country: 'Jamaica' },
    { code: 'NAS', city: 'Nassau', name: 'Lynden Pindling Intl', country: 'Bahamas' },
    { code: 'BGI', city: 'Bridgetown', name: 'Grantley Adams Intl', country: 'Barbados' },
    {
        code: 'POS',
        city: 'Port of Spain',
        name: 'Piarco Intl Airport',
        country: 'Trinidad and Tobago',
    },
    { code: 'GEO', city: 'Georgetown', name: 'Cheddi Jagan Intl', country: 'Guyana' },
    { code: 'PBM', city: 'Paramaribo', name: 'Johan Adolf Pengel Intl', country: 'Suriname' },
    { code: 'CAY', city: 'Cayenne', name: 'Cayenne-Félix Eboué', country: 'French Guiana' },
    { code: 'UIO', city: 'Quito', name: 'Mariscal Sucre Intl', country: 'Ecuador' },
    { code: 'GYE', city: 'Guayaquil', name: 'José Joaquín de Olmedo', country: 'Ecuador' },
    { code: 'LPA', city: 'Gran Canaria', name: 'Gran Canaria Airport', country: 'Spain' },
    { code: 'TFS', city: 'Tenerife', name: 'Tenerife South Airport', country: 'Spain' },
    { code: 'PMI', city: 'Palma de Mallorca', name: 'Palma de Mallorca Airport', country: 'Spain' },
    { code: 'IBZ', city: 'Ibiza', name: 'Ibiza Airport', country: 'Spain' },
    { code: 'MAH', city: 'Menorca', name: 'Menorca Airport', country: 'Spain' },
    { code: 'FUE', city: 'Fuerteventura', name: 'Fuerteventura Airport', country: 'Spain' },
    { code: 'ACE', city: 'Lanzarote', name: 'César Manrique-Lanzarote', country: 'Spain' },
    { code: 'SPC', city: 'La Palma', name: 'La Palma Airport', country: 'Spain' },
    { code: 'VDE', city: 'El Hierro', name: 'El Hierro Airport', country: 'Spain' },
    { code: 'GMZ', city: 'La Gomera', name: 'La Gomera Airport', country: 'Spain' },
    { code: 'OPO', city: 'Porto', name: 'Francisco Sá Carneiro', country: 'Portugal' },
    { code: 'FAO', city: 'Faro', name: 'Faro Airport', country: 'Portugal' },
    { code: 'FNC', city: 'Madeira', name: 'Madeira Airport', country: 'Portugal' },
    { code: 'PDL', city: 'Ponta Delgada', name: 'João Paulo II Airport', country: 'Portugal' },
    { code: 'TER', city: 'Terceira', name: 'Lajes Field', country: 'Portugal' },
    { code: 'HOR', city: 'Horta', name: 'Horta Airport', country: 'Portugal' },
    { code: 'PIX', city: 'Pico', name: 'Pico Airport', country: 'Portugal' },
    { code: 'SJZ', city: 'São Jorge', name: 'São Jorge Airport', country: 'Portugal' },
    { code: 'GRW', city: 'Graciosa', name: 'Graciosa Airport', country: 'Portugal' },
    { code: 'FLW', city: 'Flores', name: 'Flores Airport', country: 'Portugal' },
    { code: 'CVU', city: 'Corvo', name: 'Corvo Airport', country: 'Portugal' },
    { code: 'SMA', city: 'Santa Maria', name: 'Santa Maria Airport', country: 'Portugal' },
    { code: 'BOD', city: 'Bordeaux', name: 'Bordeaux-Mérignac Airport', country: 'France' },
    { code: 'TLS', city: 'Toulouse', name: 'Toulouse-Blagnac Airport', country: 'France' },
    { code: 'NTE', city: 'Nantes', name: 'Nantes Atlantique Airport', country: 'France' },
    { code: 'LIL', city: 'Lille', name: 'Lille Airport', country: 'France' },
    { code: 'SXB', city: 'Strasbourg', name: 'Strasbourg Airport', country: 'France' },
    { code: 'RNS', city: 'Rennes', name: 'Rennes–Saint-Jacques', country: 'France' },
    { code: 'BES', city: 'Brest', name: 'Brest Bretagne Airport', country: 'France' },
    { code: 'MPL', city: 'Montpellier', name: 'Montpellier–Méditerranée', country: 'France' },
    { code: 'BIA', city: 'Bastia', name: 'Bastia-Poretta Airport', country: 'France' },
    { code: 'AJA', city: 'Ajaccio', name: 'Ajaccio Napoleon Bonaparte', country: 'France' },
    { code: 'CLY', city: 'Calvi', name: 'Calvi – Sainte-Catherine', country: 'France' },
    { code: 'FSC', city: 'Figari', name: 'Figari–Sud Corse Airport', country: 'France' },
    { code: 'PSA', city: 'Pisa', name: 'Pisa Intl Airport', country: 'Italy' },
    { code: 'FLR', city: 'Florence', name: 'Florence Airport', country: 'Italy' },
    { code: 'BLQ', city: 'Bologna', name: 'Bologna Guglielmo Marconi', country: 'Italy' },
    { code: 'TRN', city: 'Turin', name: 'Turin Airport', country: 'Italy' },
    { code: 'GOA', city: 'Genoa', name: 'Genoa Cristoforo Colombo', country: 'Italy' },
    { code: 'VRN', city: 'Verona', name: 'Verona Villafranca Airport', country: 'Italy' },
    { code: 'TSF', city: 'Treviso', name: 'Treviso Airport', country: 'Italy' },
    { code: 'TSF', city: 'Trieste', name: 'Trieste – Friuli Venezia Giulia', country: 'Italy' },
    { code: 'AOI', city: 'Ancona', name: 'Ancona Falconara Airport', country: 'Italy' },
    { code: 'PEG', city: 'Perugia', name: "Perugia San Francesco d'Assisi", country: 'Italy' },
    { code: 'PSR', city: 'Pescara', name: 'Abruzzo Airport', country: 'Italy' },
    { code: 'BRI', city: 'Bari', name: 'Bari Karol Wojtyła Airport', country: 'Italy' },
    { code: 'BDS', city: 'Brindisi', name: 'Brindisi Airport', country: 'Italy' },
    { code: 'SUF', city: 'Lamezia Terme', name: 'Lamezia Terme Intl', country: 'Italy' },
    { code: 'REG', city: 'Reggio Calabria', name: 'Reggio Calabria Airport', country: 'Italy' },
    { code: 'CTA', city: 'Catania', name: 'Catania-Fontanarossa', country: 'Italy' },
    { code: 'TPS', city: 'Trapani', name: 'Vincenzo Florio Airport', country: 'Italy' },
    { code: 'LMP', city: 'Lampedusa', name: 'Lampedusa Airport', country: 'Italy' },
    { code: 'PNL', city: 'Pantelleria', name: 'Pantelleria Airport', country: 'Italy' },
    { code: 'CAG', city: 'Cagliari', name: 'Cagliari Elmas Airport', country: 'Italy' },
    { code: 'OLB', city: 'Olbia', name: 'Olbia Costa Smeralda', country: 'Italy' },
    { code: 'AHO', city: 'Alghero', name: 'Alghero-Fertilia Airport', country: 'Italy' },
    { code: 'ZAG', city: 'Zagreb', name: 'Zagreb Airport', country: 'Croatia' },
    { code: 'SPU', city: 'Split', name: 'Split Airport', country: 'Croatia' },
    { code: 'DBV', city: 'Dubrovnik', name: 'Dubrovnik Airport', country: 'Croatia' },
    { code: 'ZAD', city: 'Zadar', name: 'Zadar Airport', country: 'Croatia' },
    { code: 'PUY', city: 'Pula', name: 'Pula Airport', country: 'Croatia' },
    { code: 'RJK', city: 'Rijeka', name: 'Rijeka Airport', country: 'Croatia' },
    { code: 'OSI', city: 'Osijek', name: 'Osijek Airport', country: 'Croatia' },
    { code: 'BWK', city: 'Bol', name: 'Brač Airport', country: 'Croatia' },
    { code: 'LSZ', city: 'Lošinj', name: 'Lošinj Airport', country: 'Croatia' },
    { code: 'LJU', city: 'Ljubljana', name: 'Ljubljana Jože Pučnik', country: 'Slovenia' },
    { code: 'MBX', city: 'Maribor', name: 'Maribor Edvard Rusjan', country: 'Slovenia' },
    { code: 'POW', city: 'Portorož', name: 'Portorož Airport', country: 'Slovenia' },
    {
        code: 'SJJ',
        city: 'Sarajevo',
        name: 'Sarajevo Intl Airport',
        country: 'Bosnia and Herzegovina',
    },
    { code: 'TZL', city: 'Tuzla', name: 'Tuzla Intl Airport', country: 'Bosnia and Herzegovina' },
    { code: 'OMO', city: 'Mostar', name: 'Mostar Intl Airport', country: 'Bosnia and Herzegovina' },
    {
        code: 'BNX',
        city: 'Banja Luka',
        name: 'Banja Luka Intl Airport',
        country: 'Bosnia and Herzegovina',
    },
    { code: 'BEG', city: 'Belgrade', name: 'Belgrade Nikola Tesla', country: 'Serbia' },
    { code: 'INI', city: 'Niš', name: 'Niš Constantine the Great', country: 'Serbia' },
    { code: 'KVO', city: 'Kraljevo', name: 'Morava Airport', country: 'Serbia' },
    { code: 'PRN', city: 'Pristina', name: 'Pristina Intl Airport', country: 'Kosovo' },
    { code: 'SKP', city: 'Skopje', name: 'Skopje Intl Airport', country: 'North Macedonia' },
    { code: 'OHD', city: 'Ohrid', name: 'Ohrid St. Paul the Apostle', country: 'North Macedonia' },
    { code: 'TIA', city: 'Tirana', name: 'Tirana Intl Airport', country: 'Albania' },
    { code: 'TGD', city: 'Podgorica', name: 'Podgorica Airport', country: 'Montenegro' },
    { code: 'TIV', city: 'Tivat', name: 'Tivat Airport', country: 'Montenegro' },
    { code: 'SOF', city: 'Sofia', name: 'Sofia Airport', country: 'Bulgaria' },
    { code: 'BOJ', city: 'Burgas', name: 'Burgas Airport', country: 'Bulgaria' },
    { code: 'VAR', city: 'Varna', name: 'Varna Airport', country: 'Bulgaria' },
    { code: 'PDV', city: 'Plovdiv', name: 'Plovdiv Airport', country: 'Bulgaria' },
    { code: 'OTP', city: 'Bucharest', name: 'Henri Coandă Intl', country: 'Romania' },
    { code: 'CLJ', city: 'Cluj-Napoca', name: 'Cluj Intl Airport', country: 'Romania' },
    { code: 'TSR', city: 'Timișoara', name: 'Timișoara Traian Vuia', country: 'Romania' },
    { code: 'IAS', city: 'Iași', name: 'Iași Intl Airport', country: 'Romania' },
    { code: 'SBZ', city: 'Sibiu', name: 'Sibiu Intl Airport', country: 'Romania' },
    { code: 'CRA', city: 'Craiova', name: 'Craiova Intl Airport', country: 'Romania' },
    { code: 'BCM', city: 'Bacău', name: 'George Enescu Intl', country: 'Romania' },
    { code: 'TGM', city: 'Târgu Mureș', name: 'Târgu Mureș Transilvania', country: 'Romania' },
    { code: 'SUJ', city: 'Satu Mare', name: 'Satu Mare Intl Airport', country: 'Romania' },
    { code: 'OMR', city: 'Oradea', name: 'Oradea Intl Airport', country: 'Romania' },
    { code: 'BAY', city: 'Baia Mare', name: 'Maramureș Intl Airport', country: 'Romania' },
    { code: 'KIV', city: 'Chișinău', name: 'Chișinău Intl Airport', country: 'Moldova' },
    { code: 'BUD', city: 'Budapest', name: 'Budapest Ferenc Liszt', country: 'Hungary' },
    { code: 'DEB', city: 'Debrecen', name: 'Debrecen Intl Airport', country: 'Hungary' },
    { code: 'BTS', city: 'Bratislava', name: 'M. R. Štefánik Airport', country: 'Slovakia' },
    { code: 'KSC', city: 'Košice', name: 'Košice Intl Airport', country: 'Slovakia' },
    { code: 'TAT', city: 'Poprad', name: 'Poprad-Tatry Airport', country: 'Slovakia' },
    { code: 'PRG', city: 'Prague', name: 'Václav Havel Airport', country: 'Czech Republic' },
    { code: 'BRQ', city: 'Brno', name: 'Brno-Tuřany Airport', country: 'Czech Republic' },
    { code: 'OSR', city: 'Ostrava', name: 'Leoš Janáček Airport', country: 'Czech Republic' },
    { code: 'PED', city: 'Pardubice', name: 'Pardubice Airport', country: 'Czech Republic' },
    { code: 'KLV', city: 'Karlovy Vary', name: 'Karlovy Vary Airport', country: 'Czech Republic' },
]);
